remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Arquitetura do Twitter]
description: [Estudo e demonstração do funcionamento da arquitetura do twitter]
